---
swagger: "2.0"
info:
  description: "Face APIs"
  version: "2.0"
  title: "Face API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "host.host.host:8080"
basePath: "/"
tags:
- name: "Face APIs"
  description: "Operations available to regular developers"
schemes:
- "https"
paths:
  /api/v2/images/{id}:
    get:
      tags:
      - "developers"
      summary: "Get base64-encoded image by id previously stored on face."
      operationId: "getUser"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id of an image"
        required: true
        type: "string"
      - name: "authorization"
        in: "header"
        description: "JWT token for authorization"
        required: true
        type: "string"
        default: "Bearer here.goes.token"
      responses:
        200:
          description: "Return image"
          schema:
            $ref: "#/definitions/ImageWithMetadata"
        400:
          description: "Bad Request"
          examples:
            noSuchKeyError:
              error: "NoSuchKeyError"
            idMissing:
              error: "Expecting 'id' in properties"
          schema:
            $ref: "#/definitions/inline_response_400"
        401:
          description: "Unauthorized"
          examples:
            headerMissing:
              error: "Authorization header missing"
            cantConnectNOS:
              error: "Unauthorized - Unable to connect to NOS"
            NOSUnauthorized:
              error: "Unauthorized"
          schema:
            $ref: "#/definitions/unauthorized"
  /api/v2/registrations:
    post:
      tags:
      - "developers"
      summary: "Register user by name and images or image links."
      description: "Accepts links for images stored on face, or images in base64 format."
      operationId: "registerUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "NameWithImageIDArray"
        description: "Name, fr_type, images array"
        required: false
        schema:
          $ref: "#/definitions/NameWithImageIDArray"
      - name: "authorization"
        in: "header"
        description: "JWT token for authorization"
        required: true
        type: "string"
        default: "Bearer here.goes.token"
      responses:
        200:
          description: "Person registered with BaiduAPI"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "Bad Request"
          examples:
            invalidJSON:
              error: "Invalid JSON"
            ParamMissing:
              error: "images parameter missing"
            imagesIsNotAList:
              error: "images must be a list"
            invalidImageOrLink:
              error: "invalid image or link"
        401:
          description: "Unauthorized"
          examples:
            headerMissing:
              error: "Authorization header missing"
            cantConnectNOS:
              error: "Unauthorized - Unable to connect to NOS"
            NOSUnauthorized:
              error: "Unauthorized"
          schema:
            $ref: "#/definitions/unauthorized"
definitions:
  NameWithImageIDArray:
    type: "object"
    properties:
      images:
        type: "array"
        example:
        - "21319a6e-b323-47b8-bd23-8b54ad7977f0"
        - "c56c852d-d126-4eae-b37e-e1a6be288401"
        - "38bc16e6-de9a-40d4-b7d3-d9cb06862ca6"
        - "=base64Image..."
        - "..."
        items:
          type: "string"
    example:
      images:
      - "21319a6e-b323-47b8-bd23-8b54ad7977f0"
      - "c56c852d-d126-4eae-b37e-e1a6be288401"
      - "38bc16e6-de9a-40d4-b7d3-d9cb06862ca6"
      - "=base64Image..."
      - "..."
  invalidJSON:
    type: "object"
    required:
    - "error"
    properties:
      error:
        type: "string"
  IdOfImage:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        format: "uuid"
  unauthorized:
    type: "object"
    properties:
      error:
        type: "string"
  ImageWithMetadata:
    type: "object"
    required:
    - "image"
    - "metadata"
    properties:
      image:
        type: "string"
        format: "base64"
        example: "/9j..."
      metadata:
        $ref: "#/definitions/ImageWithMetadata_metadata"
    example:
      image: "/9j..."
  inline_response_400:
    properties:
      error:
        type: "string"
  inline_response_200:
    properties:
      name:
        type: "string"
        example: "Andrew"
      written:
        type: "string"
        example: "ok"
      id:
        type: "string"
        example: "cbdcf059_2f52_4636_b79a_c79aa46590f0"
    example:
      written: "ok"
      id: "cbdcf059_2f52_4636_b79a_c79aa46590f0"
  ImageWithMetadata_metadata_observation_metadata_FR_metadata:
    properties:
      group_id:
        type: "string"
        example: "dataset1"
      score:
        type: "number"
        example: 99.900000000000005684341886080801486968994140625
      user_info:
        type: "string"
        example: "Andrew"
    example:
      score: 99.900000000000005684341886080801486968994140625
      group_id: "dataset1"
      user_info: "Andrew"
  ImageWithMetadata_metadata_observation_metadata_event_metadata:
    properties:
      camera_name:
        type: "string"
        example: "0"
      quality:
        type: "integer"
        example: 1
      ts:
        type: "number"
        example: 12839
    example:
      camera_name: "0"
      quality: 1
      ts: 12839
  ImageWithMetadata_metadata_observation_metadata:
    properties:
      FR_metadata:
        $ref: "#/definitions/ImageWithMetadata_metadata_observation_metadata_FR_metadata"
      event_metadata:
        $ref: "#/definitions/ImageWithMetadata_metadata_observation_metadata_event_metadata"
    example:
      FR_metadata:
        score: 99.900000000000005684341886080801486968994140625
        group_id: "dataset1"
        user_info: "Andrew"
      event_metadata:
        camera_name: "0"
        quality: 1
        ts: 12839
  ImageWithMetadata_metadata:
    properties:
      observation_id:
        type: "integer"
        example: 1
      observation_metadata:
        $ref: "#/definitions/ImageWithMetadata_metadata_observation_metadata"
      observation_type:
        type: "string"
        example: "thumbnail_captured"
      person_id:
        type: "string"
        example: "cbdcf059_2f52_4636_b79a_c79aa46590f0"
    example:
      observation_id: 1
      observation_metadata:
        FR_metadata:
          score: 99.900000000000005684341886080801486968994140625
          group_id: "dataset1"
          user_info: "Andrew"
        event_metadata:
          camera_name: "0"
          quality: 1
          ts: 12839
      observation_type: "thumbnail_captured"
      person_id: "cbdcf059_2f52_4636_b79a_c79aa46590f0"
