---
openapi: 3.0.1
info:
  title: HOS-mouth
  description: HOS-mouth service that allow to access data from cameras via SSE stream
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
    extensions: {}
  version: "2.0"
  extensions: {}
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: /
tags:
- name: observations
  description: Provide SSE stream with OUT topic data
  extensions: {}
paths:
  /observations:
    post:
      tags:
      - observations
      summary: Provide SSE stream with raw data from OUT topic
      responses:
        200:
          description: A successful operation returns status code 200 (OK).
          content: {}
          extensions: {}
        400:
          description: An invalid operation returns status code 400 (Bad Request).
          content: {}
          extensions: {}
      extensions: {}
    extensions: {}
components: {}
